apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hola-gitops
  namespace: argocd
spec:
  project: default
  source:
    # CAMBIA TU-USUARIO por tu usuario de GitHub
    repoURL: https://github.com/vicoscanseco/argocd-demo.git
    targetRevision: main
    path: apps/hola-gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
